version: '3.8'
services:
  mysqldb:
    container_name: my_manager_db
    image: mysql:8.3.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
